apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountsdb-deployment
  labels:
    app: accountsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountsdb
  template:
    metadata:
      labels:
        app: accountsdb
    spec:
      containers:
      - name: accountsdb
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: MYSQL_ACCOUNTS_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: eazybank-configmap
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom: 
            configMapKeyRef:
              name: eazybank-configmap
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: eazybank-configmap
              key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: accountsdb
spec:
  selector:
    app: accountsdb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306