apiVersion: v1
kind: ConfigMap
metadata:
  name: eazybank-configmap
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
  CONFIGSERVER_APPLICATION_NAME: configserver
  EUREKA_APPLICATION_NAME: eurekaserver
  ACCOUNTS_APPLICATION_NAME: accounts
  LOANS_APPLICATION_NAME: loans
  CARDS_APPLICATION_NAME: cards
  GATEWAY_APPLICATION_NAME: gatewayserver
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: eazybank
  MYSQL_PASSWORD: eazybank
  MYSQL_ACCOUNTS_DATABASE: accountsdb
  MYSQL_LOANS_DATABASE: loansdb
  MYSQL_CARDS_DATABASE: cardsdb
  SPRING_DATASOURCE_URL_ACCOUNTS: jdbc:mysql://accountsdb:3307/accountsdb
  SPRING_DATASOURCE_URL_LOANS: jdbc:mysql://loansdb:3308/loansdb
  SPRING_DATASOURCE_URL_CARDS: jdbc:mysql://cardsdb:3309/cardsdb
  SPRING_DATASOURCE_USERNAME: eazybank
  SPRING_DATASOURCE_PASSWORD: eazybank